### ISSUE TITLE
Could you provide more details about this project?

### ISSUE THREAD

**Issue by tanjuntao** [OpenMined/PSI#100]
## Question
**Describe your question in ONE SENTENCE.**
1. Can both parties get the intersection itself instead of its cardinality ?
2. What PSI protocols are implemented in this project?

**Comment by schoppmp** [comment]
1. The result will always be returned to the client, who can choose to share it with the server. If you want to reveal the intersection itself and not only its cardinality, set `reveal_intersection = true` when constructing client and the server.
2. We implemented a standard Diffie-Hellman-based PSI protocol, augmented with a bloom filter for more efficient communication. A description can be found [here in the source code](https://github.com/OpenMined/PSI/blob/master/private_set_intersection/cpp/psi_client.h#L29). We have an upcoming workshop paper describing the protocol, which will have more details.

**Comment by schoppmp** [comment]
Our paper on this PSI library can now be found on [arxiv](https://arxiv.org/pdf/2011.09350.pdf). It includes a formal description of our protocols. I hope this answers your second question, let me know if not.

**Comment by tanjuntao** [comment]
Yes! Thanks for your explanation!
