### ISSUE TITLE
PSI builds failing

### ISSUE THREAD

**Issue by EssieYee** [OpenMined/PSI#101]
## Description
When I try PyVertical (https://github.com/OpenMined/PyVertical), there are some problems in running build-psi.sh. The ERROR infomation is as follows:

INFO: Repository rule 'org_openmined_psi' returned: {"remote": "https://github.com/OpenMined/PSI", "commit": "ca2866e3c70a018ed9a5a2e7af5bcbd31dc49df9", "shallow_since": "2020-14-07", "init_submodules": True, "verbose": False, "strip_prefix": "", "patches": [], "patch_tool": "patch", "patch_args": ["-p0"], "patch_cmds": [], "name": "org_openmined_psi"}
ERROR: /home/tanghengzhu/.cache/bazel/_bazel_tanghengzhu/9b06aa84c50b71eaea609540d6aa319b/external/org_openmined_psi/private_set_intersection/javascript/toolchain/cc_toolchain_config.bzl:171:17: **name 'CcToolchainConfigInfo' is not defined**
ERROR: error loading package '': **Extension 'private_set_intersection/javascript/toolchain/cc_toolchain_config.bzl' has errors**
ERROR: error loading package '': Extension 'private_set_intersection/javascript/toolchain/cc_toolchain_config.bzl' has errors
INFO: Elapsed time: 8.584s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

## How to Reproduce
1. Installed bazel
2. run the build script with .github/workflows/scripts/build-psi.sh..'

## Expected Behavior
This should generate a _psi_bindings.so file and place it in src/psi/.

## System Information
 - OS Version: Linux sigmaster 3.10.0 Red Hat 4.8.5-39
 - Language Version: python 3.7.8
 - Package Manager Version: Conda 4.6.14
 - Bazel Version: 1.0.0 (3.7.1 was also tried)

**Comment by EssieYee** [comment]
I ran the program on another server, and the previous issue has been solved. However, there are some new problems.

Target @org_openmined_psi//private_set_intersection/python:private_set_intersection up-to-date (nothing to build)
INFO: Elapsed time: 36.477s, Critical Path: 26.25s
INFO: 630 processes: 2 internal, 628 linux-sandbox.
INFO: Build completed successfully, 630 total actions
cp: cannot stat 'bazel-bin/external/org_openmined_psi/private_set_intersection/python/_psi_bindings.so': No such file or directory

**Comment by bcebere** [comment]
Hello.

The issues are unrelated:
 - For the first one, seems like an issue from the JS bindings. maybe @s0l0ist can help you here.
 - For the second, is looks like you didn't compile the python bindings. Are you using the master branch?

**Comment by schoppmp** [comment]
I think the first issue was due to the Bazel version, but it has been fixed if I understood @EssieYee correctly.
For the second issue, are you running the script from the top-level PyVertical directory? I think it won't work when you run it from another directory.

**Comment by bcebere** [comment]
In the "python wheel" branch I renamed the python extension, to fit the OM requirements/to make setuptools work as well.

So, on that branch, the error is ok, you can wait for that merge and you can add openmined.psi in your requirement.txt file directly, instead of building the library from scratch.

**Comment by EssieYee** [comment]
Thanks for your response!  @schoppmp 's suggestion is very useful and I have solved this issue.
