### ISSUE TITLE
Is the security of the Golomb-based scheme solely based on having a large domain and a strong hash?

### ISSUE THREAD

**Issue by jellevos** [OpenMined/PSI#123]
## Question
Is the security of the Golomb-based scheme solely based on having a large domain and a strong hash?

## Further Information
First, this repository looks very nice! Congratulations on the project and the support for so many different languages. I noticed that you have switched from Bloom filters to Golomb-coded sets since they are more compact. However, looking through the code I got the impression that the receiver would be able to see the entire Golomb-encodings. Does this not allow the receiver to retrieve the entire encoded set if the domain is small enough (or the hash is not strong)?

**Comment by s0l0ist** [comment]
In short, yes.

The receiver does indeed see the encoded set. However, the security assumption is that without knowledge of the original set and with a sufficiently large domain, the encoded set alone does not provide enough information to recover the original set.
