### ISSUE TITLE
How to install and run in pycharm?

### ISSUE THREAD

**Issue by UrsaEli** [OpenMined/PSI#130]
How How to install and run this package in pycharm?

I tried pip3, conda. pip installed openminded.psi, but conda is not able to find the package, and in pycharm, it is not able to import what pip3 installed.

Thanks for your help.

**Comment by s0l0ist** [comment]
Hi @UrsaEli, we do not publish a distribution for conda so it will fail in the way you described.

Regarding pycharm, could you try again using the latest release `1.0.0`? An example of how to import it is in the [test](https://github.com/OpenMined/PSI/blob/master/private_set_intersection/python/tests.py).

**Comment by s0l0ist** [comment]
Closing this issue, but re-open if it is still causing a problem.
