### ISSUE TITLE
When Client and Server items are in some certain sizes, server.CreateSetupMessage raise ValueError: basic_string::resize

### ISSUE THREAD

**Issue by chesterxgchen** [OpenMined/PSI#143]
## Description
When client items size and server items size are in certain values, the PSI code throw basic_string::resize Value Error. 
For example, using the tests.py  https://github.com/OpenMined/PSI/blob/master/private_set_intersection/python/tests.py#L28

if we change the client items and server items range into the following values: 
client_items = ["Element " + str(i) for i in range(333334)]
server_items = ["Element " + str(2 * i) for i in range(397)]

You should be able to get the exception 
```
File ~/nvflare-env2/lib/python3.8/site-packages/openmined_psi/__init__.py:140, in server.CreateSetupMessage(self, fpr, num_client_inputs, inputs)
    129 def CreateSetupMessage(
    130     self, fpr: float, num_client_inputs: int, inputs: List[str]
    131 ) -> ServerSetup:
    132     """Create a setup message from the server's dataset to be sent to the client.
    133     Args:
    134         fpr: the probability that any query of size `num_client_inputs` will result in a false positive.
   (...)
    138         A Protobuf with the setup message.
    139     """
--> 140     interm_msg = self.data.CreateSetupMessage(fpr, num_client_inputs, inputs).save()
    141     msg = ServerSetup()
    142     msg.ParseFromString(interm_msg)

ValueError: basic_string::resize
```
## How to Reproduce
1. check the code in  https://github.com/chesterxgchen/psi_mpc_related/blob/main/psi/psi_intersect.ipynb
    command Cell No. 5 should re-produce the error. 
    The code in this notebook is essentially the same as   https://github.com/OpenMined/PSI/blob/master/private_set_intersection/python/tests.py#L28  

3. pip install the openmined.psi
4. start the jupyter notebook with https://github.com/chesterxgchen/psi_mpc_related/blob/main/psi/psi_intersect.ipynb
5. execute the import the psi packages, and def dup() function, then run cmd 5, to see error

## Expected Behavior
No error

## Screenshots
![image](https://user-images.githubusercontent.com/512707/210691777-171cef7c-fb28-4aee-9395-2ceb594df647.png)

## System Information
 - OS: Ubuntu 
 - OS Version: 20.04
 - Openmined PSI version:  openmined.psi-0.3.5 ( directly downloaded from Pipy)
 - Language Version: python 3.8.16 (default, Dec  7 2022, 01:12:06)
 - Package Manager: Version pip 22.3.1
 - Browser (if applicable):  NA
 - Browser Version (if applicable): NA

## Additional Context
We experience this issue while testing our openmined-based PSI solution

**Comment by s0l0ist** [comment]
This is a bug with the `GCS` data structure and having an extremely low `fpr`. The data structure enum (GCS, BloomFilter) was added much later and was never exposed as a configurable parameter in Python's binding for `CreateSetupMessage`. We will publish a new release to allow you to specify `BloomFilter` which temporarily solves the underlying problem.

**Comment by s0l0ist** [comment]
This has been fixed in https://github.com/OpenMined/PSI/releases/tag/v1.0.1

**Comment by s0l0ist** [comment]
Yep, looks like smaller false positive rate causes the backing GCS datastructure to try and allocate too much memory. This is 'fixed' in the sense that you must use the `psi.DataStructure.BLOOM_FILTER` enum and pass it into `CreateSetupMessage` as the last argument.

**Comment by s0l0ist** [comment]
Ah yes, I put the param outside of the function. Oops.

**Comment by s0l0ist** [comment]
Looking at the example code, it looks like the client has many more values than the server. This will yield much higher chances of receiving a false positive value in return and isn't the intended way of how to use this library. 

The protocol is asymmetric in the sense that both client and server sets can be different sizes, but the real use case is for when the client has much fewer items in its set and wants to check against a server with many more items in its set. 

If you flip the client and server set sizes, you should get more reasonable results in expectation of the FPR you've set.

**Comment by s0l0ist** [comment]
I see, yeah this is a bug. I'll investigate.

**Comment by s0l0ist** [comment]
There was a bug that produced more erroneous results than normal; however, it is quite possible for false positives to manifest themselves in the form of intersection index values that are out of range of the original client set. Checkout the my comments in the [PR](https://github.com/OpenMined/PSI/pull/151) to handle those cases.
