### ISSUE TITLE
Question regarding python version requirements >=3.8.10

### ISSUE THREAD

**Issue by chesterxgchen** [OpenMined/PSI#153]
## Question
Is it possible to support python version >=3.7.0 ? 

## Further Information
based on the pypi page, https://pypi.org/project/openmined.psi/

Meta
License: Apache 2.0

Author: OpenMined

Requires: Python >=3.8.10

PSI requires 3.8.10+, is it possible to support 3.7.0+ ? 

## Screenshots

n/a

## System Information
 Ubuntu
## Additional Context

NVFLARE is currently requires python >=3.7.  my current pip install openmined.psi failed in CI env.

**Comment by s0l0ist** [comment]
My initial reasoning for 3.8 was that it was the first version to give support M1 Macs. In addition, 3.8.10 is required by the (new) wheel names on Linux. 

Having made some of these changes in the past, I no longer think it is difficult to try and support 3.7 with a notable exception that it will not work on arm64 which maybe fine for the majority of use cases. 

I think the only thing I need to do is use manylinux2014 as the wheel name just for 3.7.

**Comment by s0l0ist** [comment]
I can try, what is the full version of python, pip, and glibc in your CI environment?

**Comment by s0l0ist** [comment]
@chesterxgchen I can try.

The main reason for not supporting 3.7 was that is it problematic for M1 Macs and the pep 600 naming convention required 3.8.10; however, I can probably carve out an exception for 3.7 if it doesn't require arm64 support.

What is the full version of python, pip, and glibc in your CI env?

**Comment by s0l0ist** [comment]
@chesterxgchen Based on our discussions earlier, is this still a needed requirement?

**Comment by s0l0ist** [comment]
@chesterxgchen, please let me know if v1.1.1 does not work in your environment.
