### ISSUE TITLE
Error in python psi for v2.0.1 on mac10.15.4  

### ISSUE THREAD

**Issue by relinda2019** [OpenMined/PSI#167]
## Description
A clear and concise description of the bug.

## How to Reproduce
1. In source code, modify  __init__.py
![modifly1](https://user-images.githubusercontent.com/39260479/229488196-65bd32a3-5c81-4854-bfe7-9849384ba49a.png)

    
3. run PSI/private_set_intersection/python/tests.py  directly

5. See error:
    
![run1](https://user-images.githubusercontent.com/39260479/229488428-1a9061be-5fa8-4129-8bef-5a2f3dee1267.png)

## System Information
 - OS: mac
 - OS Version: 10.15.4
 - Language Version: python3.9

## Additional Context
Error: AttributeError: module '_openmined_psi' has no attribute 'data_structure'
Thanks very much!!

**Comment by s0l0ist** [comment]
You're changing the import path to something that doesn't exist.

This was a breaking change sometime back after (I think) 1.0.0. 

Keep the import path structure the same as in the tests and you will be fine.
