### ISSUE TITLE
not a supported wheel on this platform

### ISSUE THREAD

**Issue by relinda2019** [OpenMined/PSI#168]
## Question
**Describe your question in ONE SENTENCE.**

## Further Information
   When I build on mac10.15.4, buile sucess, but failed when install.

```
cd PSI/private_set_intersection/python
pip install requirements.in
pip install requirements.txt
cd ~/PSI
bazel build -c opt private_set_intersection/python:wheel
ls bazel-bin/private_set_intersection/python/openmined.psi-2.0.1-INTERPRETER-ABI-macosx_12_0_x86_64.whl
python private_set_intersection/python/rename.py 
pip install ./bazel-bin/private_set_intersection/python/openmined.psi-2.0.1-cp39-cp39-macosx_12_0_x86_64.whl
```

## Screenshot
![pic1](https://user-images.githubusercontent.com/39260479/230252942-4f644236-7d01-4491-a0b5-17c3934745e8.png)

## System Information
 - OS: mac
 - OS Version: 'macOS-10.15.4-x86_64-i386-64bit'
 - Language Version: python 3.9.5
 - Package Manager Version: conda 4.3

**Comment by s0l0ist** [comment]
Hi @relinda2019, the python `rename.py` script is very rudimentary and it's possible that we do not build correctly for older MacOSX versions. I also do not have a compatible machine to test your OS version or architecture (x86_64).

Can you try manually renaming your wheel to the following versions and try to pip install each time?

Change `./bazel-bin/private_set_intersection/python/openmined.psi-2.0.1-cp39-cp39-macosx_12_0_x86_64.whl
` to the following:

```
./bazel-bin/private_set_intersection/python/openmined.psi-2.0.1-cp39-cp39-macosx_11_0_x86_64.whl
pip install ./bazel-bin/private_set_intersection/python/openmined.psi-2.0.1-cp39-cp39-macosx_11_0_x86_64.whl

... if that doesn't work, then try renaming to:
./bazel-bin/private_set_intersection/python/openmined.psi-2.0.1-cp39-cp39-macosx_10_15_x86_64.whl
pip install ./bazel-bin/private_set_intersection/python/openmined.psi-2.0.1-cp39-cp39-macosx_10_15_x86_64.whl
```
