### ISSUE TITLE
OpenMined PSI and Google’s Private Join and Compute

### ISSUE THREAD

**Issue by ruidazeng** [OpenMined/PSI#208]
Has any comparative analysis been done between [OpenMined’s PSI](https://github.com/OpenMined/PSI) and [Google’s Private Join and Compute](https://github.com/Google/private-join-and-compute)? Specifically interested in differences in performance, security, scalability, and ease of integration. This would be helpful for understanding trade-offs in various use cases.

Would OpenMined consider publishing such an analysis, or is this open to community contributions?

**Comment by schoppmp** [comment]
This repository is in fact based on Google's PJC, or more concretely, @s0l0ist's fork of it: https://github.com/s0l0ist/private-join-and-compute/
I don't think there are any performance differences, apart from the overhead of the language wrappers.
Hope this helps.

**Comment by s0l0ist** [comment]
I'll also add that my fork is really just updating dependencies and using the latest bzlmod structure: https://github.com/google/private-join-and-compute/pull/51/files
