### ISSUE TITLE
Fix workflow for MacOS

### ISSUE THREAD

**Issue by schoppmp** [OpenMined/PSI#36]
The MacOS CI workflow [currently fails](https://github.com/OpenMined/PSI/pull/34/checks?check_run_id=668331151) at installing dependencies because it doesn't find `apt`. I think we need to have a different install script for Mac. Maybe outsource the install script to a shell script so that the tests.yml can be the same for all platforms?

**Comment by s0l0ist** [comment]
Looks like apt has been removed for [some time now](https://stackoverflow.com/questions/46812650/why-doesnt-the-annotation-processing-tool-apt-not-operate-after-installing-ja)

**Comment by schoppmp** [comment]
Fixed in e88faed
