### ISSUE TITLE
Request for GetPrivateKeyBytes to return a vector<uint8_t>

### ISSUE THREAD

**Issue by s0l0ist** [OpenMined/PSI#44]
### Problem
`PSICardinalityServer::GetPrivateKeyBytes()` returns a binary string containing the private key.

Several language bindings do not play nicely with binary strings resulting in various workarounds that are fragile. This is especially true for JavaScript and Go that don't play nicely with **bindings** handling binary strings.

### Proposal
Suggestion to change the output to a `vector<uint8_t>` for better interoperability our current and future bindings.

**Comment by bcebere** [comment]
Unfortunately, for the Go/cgo bindings it is not possible, because they require a C interface to work with.
