### ISSUE TITLE
Python Bazel builds fail on Windows

### ISSUE THREAD

**Issue by pavlos-p** [OpenMined/PSI#77]
## Description
I am trying to execute a python test using `bazel test //private_set_intersection/python:tests --test_output=all` or a benchmark using `bazel run -c opt //private_set_intersection/python:benchmarks --test_output=all` but the bazel builds fail.

On my Ubuntu WSL, they work fine as intended.

## How to Reproduce
1. Attempt to build the test on Windows

## Expected Behavior
Build to be completed successfully.

## Screenshots
![image](https://user-images.githubusercontent.com/44439128/87555072-de089380-c6ac-11ea-947e-2c9aac13bfc9.png)

## System Information
 - OS: Microsoft Windows 10 Pro
 - OS Version: 10.0.19041 Build 19041
 - Language Version: Python 3.7, 3.8
 - Bazel Version: Bazel 3.3.1

**Comment by TTitcombe** [comment]
Hi @s0l0ist, is there any update on this?
